/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MutilTransfer__factory } from "./MutilTransfer__factory";
export { Erc20__factory } from "./Erc20__factory";
